---
- hosts: localhost 
  become: yes
  
  
  roles:
  - { role: vagrant_role, when: ansible_system == 'Linux' }

- hosts: database
  become: yes

  roles:
  - { role: mysql, when: ansible_system == 'Linux' }


  

