all:
  children:
    localhost:
      hosts:
        localhost1:
          ansible_host: 127.0.0.1
          ansible_connection: local
    database: 
      hosts:
        database1:
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2224
