all:
  children:
    localhost:
      hosts:
        localhost1:
          ansible_host: 127.0.0.1
          ansible_connection: local
    database: 
      hosts:
        database1:
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2224
    wordpress:
      hosts:
        wordpress1:
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2225
        wordpress2:
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2226
    haproxy:
      hosts:
        haproxy1: 
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2223
    monitoring:
      hosts:
        monitor1:
          ansible_ssh_host: 127.0.0.1
          ansible_ssh_port: 2227
          
