---
# tasks file for mysql

- name: Install the MySQL packages
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: 
    - mysql-server
    - python3-pymysql

- name: set password for root user
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: save root password in .my.cnf
  template:
    src: root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: create a new database
  mysql_db:
    name: "{{ mysql_db }}"
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: new user 
  mysql_query:
    query: 
      - CREATE USER 'bonzi3'@'%' IDENTIFIED BY '123';
      - GRANT ALL PRIVILEGES ON *.* TO 'bonzi3'@'%' WITH GRANT OPTION;
      - FLUSH PRIVILEGES;

#- name: create database user
#  mysql_user:
#    name: "{{ mysql_user_name }}"
#    password: "{{ mysql_user_password }}"
#    priv: "{{ mysql_priv }}"
#    state: present

- name: replace bind-address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: ^(bind-address).*
    line: bind-address = 0.0.0.0
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart MySQL
  
    
