---
# tasks file for mysql

- name: Install the MySQL packages
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: 
    - mysql-server
    - mysql-client
    - python3-pymysql

- name: set password for root user
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: save root password in .my.cnf
  template:
    src: root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: create a new database
  mysql_db:
    name: "{{ mysql_db }}"
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: create database user
  mysql_user:
    name: "{{ mysql_user_name }}"
    password: "{{ mysql_user_password }}"
    priv: '*.*:ALL'
    state: present

- name: Remove the test database
  mysql_db: 
    name: "{{ mysql_db }}" 
    state: absent
  notify:
    - Restart MySQL

