---
# tasks file for vagrant_role
    
- name: Update and upgrade Ubuntu  
  apt: 
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true 
  
- name: Install virtualbox
  apt:
    name: virtualbox
    state: latest

- name: Copy files
  copy: src={{ item }} dest={{ destin_folder }} mode=0555
  loop:
    - "vagrant_2.2.19_x86_64.deb"

- name: Install Vagrant
  command: apt install {{ destin_folder }}/vagrant_2.2.19_x86_64.deb

#- name: New rules
#  command: chown -R {{ user_name }}:{{ user_name }} {{ destin_folder }}/{{ var_folder }}

- name: In Folder
  command: chdir={{ destin_folder }} vagrant up  
  become: False   
  become_user: dmitriy